"DOTAHeroes"
{
	//=======================================
	//	White Saber(Extra) - Gawain
	//=======================================
	"npc_dota_hero_gawain"
	{
		"override_hero"					"npc_dota_hero_omniknight"
		"DisableWearables" 				"1"
		"Model"							"models/gawain/gawain.vmdl"
		//"Model"						"models/development/invisiblebox.vmdl"
		"ModelScale"					"1.00"
		//"HeroID"						"127"
		"DrawParticlesWhileHidden" 		"1"

		"AbilityLayout"					"6"
		"Ability1"						"gawain_heat"
		"Ability2"						"gawain_blade_of_the_devoted"
		"Ability3"						"gawain_sun_of_galatine"
		"Ability4"						"fate_empty1"		
		"Ability5"						"fate_empty8"
		"Ability6"						"gawain_excalibur_galatine"
		"Ability7"						"gawain_saint"
		"Ability8"						"gawain_blessing_of_fairy"
		"Ability9"						"gawain_excalibur_galatine_detonate"
		"Ability10"						"presence_detection_passive"
		"Ability11"						"attribute_bonus_custom"
		"Ability12"						"gawain_excalibur_galatine_combo"
		"Ability13"						"gawain_excalibur_galatine_detonate_combo"		

		"Combo"							"gawain_excalibur_galatine_combo"
		"AttributeNumber"				"4"
		"Attribute1"					"gawain_attribute_blessing_of_fairy"
		"Attribute2"					"gawain_attribute_res_sov"
		"Attribute3"					"gawain_attribute_saint_num"
		"Attribute4"					"gawain_attribute_belt"
		//"Attribute5"					"gawain_attribute_eclipse"

		"StatusHealth"					"1250"
		"StatusHealthRegen"				"7.0"
		"StatusMana"					"1000"
		"StatusManaRegen"				"4.0"
		
		"ArmorPhysical"					"6"
		"MagicalResistance"				"20"
		
		"AttackCapabilities"			"DOTA_UNIT_CAP_MELEE_ATTACK"
		"AttackRange"					"185"
		"AttackDamageMin"				"52"
		"AttackDamageMax"				"52"
		"AttackRate"					"0.9"
		
		"AttributePrimary"				"DOTA_ATTRIBUTE_STRENGTH"
		"AttributeBaseStrength"			"0"
		"AttributeStrengthGain"			"1.3"
		"AttributeBaseAgility"			"0"
		"AttributeAgilityGain"			"0.9"
		"AttributeBaseIntelligence"		"0"
		"AttributeIntelligenceGain"		"0.7"
		
		"MovementSpeed"					"340"
		"MovementTurnRate"				"0.8"

		"VisionDaytimeRange"			"850"
		"VisionNighttimeRange"			"850"
	}
}