#base "gawain_heat.kv"
#base "gawain_blade_of_the_devoted.kv"

"DOTAAbilities"
{	
	//=================================================================================================================
	// Gawain : Numeral of the Saint
	//=================================================================================================================
	"gawain_saint"
	{
		"BaseClass"						"ability_datadriven"
		"AbilityBehavior"				"DOTA_ABILITY_BEHAVIOR_PASSIVE | DOTA_ABILITY_BEHAVIOR_HIDDEN"
		"AbilityTextureName"			"custom/gawain_saint"
		"MaxLevel"						"1"
		"RequiredLevel"					"25"
		"LevelsBetweenUpgrades"			"1"
		
		"AbilitySpecial"
		{
			"01"
			{
				"var_type"				"FIELD_INTEGER"
				"bonus_stat"			"3"
			}
		}
		
		"OnSpelLStart"
		{
		}
		
		"Modifiers"
		{
			"modifier_gawain_saint_bonus"
			{
				"Passive"			"1"
				"IsHidden"			"1"

				"Properties"
				{
					"MODIFIER_PROPERTY_HEALTH_REGEN_CONSTANT"		"%bonus_stat"
					"MODIFIER_PROPERTY_PHYSICAL_ARMOR_BONUS"		"%bonus_stat"
					"MODIFIER_PROPERTY_STATS_STRENGTH_BONUS"		"%bonus_stat"
					"MODIFIER_PROPERTY_STATS_AGILITY_BONUS"			"%bonus_stat"
					"MODIFIER_PROPERTY_STATS_INTELLECT_BONUS"		"%bonus_stat"
				}
			}
		}
	}

	//=================================================================================================================
	// Gawain : Blessing of Fairy
	//=================================================================================================================
	"gawain_blessing_of_fairy"
	{
		"BaseClass"						"ability_datadriven"
		"AbilityBehavior"				"DOTA_ABILITY_BEHAVIOR_PASSIVE | DOTA_ABILITY_BEHAVIOR_HIDDEN"
		"AbilityTextureName"			"custom/gawain_attribute_blessing_of_fairy"
		"MaxLevel"						"1"
		//"RequiredLevel"					"25"
		//"LevelsBetweenUpgrades"			"1"
		"AbilityCooldown"				"60"

		"precache"
		{
			"particle"					"particles/items_fx/aegis_timer.vpcf"
		}

		"AbilitySpecial"
		{
			"01"
			{
				"var_type"				"FIELD_INTEGER"
				"health_regain"			"350"
			}
			"02"
			{
				"var_type"				"FIELD_INTEGER"
				"health_regeneration"	"100"
			}
			"03"
			{
				"var_type"				"FIELD_INTEGER"
				"duration"				"5"
			}
		}

		
		"OnSpellStart"
		{
			"ApplyModifier"
			{
				"ModifierName"			"modifier_gawain_revive"
				"Target"				"CASTER"
			}
		}

		"Modifiers"
		{
			"modifier_gawain_revive"
			{
				"Passive"				"1"
				"IsHidden"				"1"
				"OnTakeDamage"
				{
					"RunScript"
					{
						"ScriptFile"	"gawain_ability"
						"Function"		"OnFairyDamageTaken"
						"DamageTaken"	"%attack_damage"
					}
				}
			}
			"modifier_gawain_blessing_cooldown"
			{
				"IsDebuff"	"1"
				"Attributes"			"MODIFIER_ATTRIBUTE_PERMANENT | MODIFIER_ATTRIBUTE_IGNORE_INVULNERABLE"
			}
			"modifier_gawain_revive_regen"
			{
				"Duration"				"5"
				"Properties"
				{
					"MODIFIER_PROPERTY_HEALTH_REGEN_CONSTANT"     		"100"
				}
			}
		}
	}

	
	//=======================================
	// Gawain : Sun of Galatine
	//=======================================
	"gawain_sun_of_galatine"
    {
        "BaseClass"                     "ability_lua"
        "ScriptFile"                    "abilities/gawain/sun_of_galatine.lua"
        "MaxLevel"						"5"
		"RequiredLevel"					"1"
		"LevelsBetweenUpgrades"			"2"
		"AbilityBehavior"				"DOTA_ABILITY_BEHAVIOR_NO_TARGET | DOTA_ABILITY_BEHAVIOR_CHANNELLED"
		"AbilityTextureName"			"custom/gawain_suns_embrace"		
		"AbilityCastAnimation" 			"ACT_DOTA_CAST_ABILITY_2"
		"AbilityCastPoint"				"0.3"
        "AbilityUnitDamageType"			"DAMAGE_TYPE_MAGICAL"        
		"AbilityCooldown"				"23"
		"AbilityManaCost"				"400"
        "AbilityChannelTime"            "2.5"

		"precache"
		{
			"particle"					"particles/custom/gawain/gawain_meltdown.vpcf"
			"particle"					"particles/custom/gawain/gawain_supernova_explosion.vpcf"
			"particle"					"particles/custom/gawain/manjinx_gawain_e.vpcf"
			"soundfile"					"soundevents/game_sounds_heroes/game_sounds_phoenix.vsndevts"
			"soundfile"					"soundevents/game_sounds_heroes/game_sounds_warlock.vsndevts"
		}

		"AbilitySpecial"
		{
			"01"
			{	
				"var_type"			"FIELD_INTEGER"
				"burn_damage"		"100 125 150 175 200"
			}
			"02"
			{
				"var_type"			"FIELD_INTEGER"
				"min_damage"		"100 175 250 325 400"
			}
			"03"
			{
				"var_type"			"FIELD_INTEGER"
				"max_damage"		"300 450 600 750 900"
			}
			"04"
			{
				"var_type"			"FIELD_INTEGER"
				"slow_perc"			"-45"
			}
			"05"
			{
				"var_type"			"FIELD_INTEGER"
				"area_of_effect"	"425"
			}
			"06"
			{
				"var_type"			"FIELD_INTEGER"
				"area_of_effect_2"	"700"
			}
			"07"
			{
				"var_type"			"FIELD_FLOAT"
				"channel_dur"		"2.5"
			}
		}
    }	

	//=================================================================================================================
	// Gawain : Excalibur Galatine
	//=================================================================================================================
	"gawain_excalibur_galatine"
	{
		// General		//------------------------------------------------------------------------------------------------------------
		"BaseClass"						"ability_datadriven"
		"MaxLevel"						"5"
		"RequiredLevel"					"1"
		"LevelsBetweenUpgrades"			"2"
		"AbilityBehavior"				"DOTA_ABILITY_BEHAVIOR_POINT | DOTA_ABILITY_BEHAVIOR_AOE"
		"AbilityUnitTargetType"			"DOTA_UNIT_TARGET_ALL"
		"AbilityUnitDamageType"			"DAMAGE_TYPE_MAGICAL"
		"AbilityTextureName"			"custom/gawain_excalibur_galatine"
		"AbilityCastAnimation" 			"ACT_DOTA_CAST_ABILITY_2"
		"AnimationPlaybackRate" 		"1.0"
		"AOERadius"						"%radius"

		
		"precache"
		{
			"particle"					"particles/units/heroes/hero_keeper_of_the_light/keeper_cast01.vpcf"
			"particle"					"particles/units/heroes/hero_lina/lina_spell_light_strike_array.vpcf"
			"particle"					"particles/custom/gawain/gawain_excalibur_galatine_orb.vpcf"
			"particle"					"particles/units/heroes/hero_ember_spirit/ember_spirit_hit.vpcf"
			"particle"					"particles/custom/saber_excalibur_circle.vpcf"
			"particle"					"particles/custom/gawain/gawain_galetine_flametrail_parent.vpcf"
			"particle"					"particles/custom/gawain/gawain_galetine_explosion_parent.vpcf"
			"soundfile"					"soundevents/game_sounds_heroes/game_sounds_lina.vsndevts"
		}
		
		"AbilityCastPoint"				"0.15"
		"AbilityCooldown"				"42"
		"AbilityManaCost"				"800"
		"AbilityCastRange"				"1500"
		
		"AbilitySpecial"
		{
			"01"
			{
				"var_type"				"FIELD_FLOAT"
				"cast_delay"			"2.00"
			}
			"02"
			{
				"var_type"				"FIELD_FLOAT"
				"damage"				"800 1050 1300 1550 1800"
			}
			"03"
			{
				"var_type"				"FIELD_INTEGER"
				"radius"				"550"
			}
			"04"
			{
				"var_type"				"FIELD_INTEGER"
				"dot_damage"			"40 70 100 130 160"
			}
			"05"
			{
				"var_type"				"FIELD_INTEGER"
				"duration"				"3"
			}
			"06"
			{
				"var_type"				"FIELD_INTEGER"
				"max_range"				"1500"
			}
		}
		
		"OnSpellStart"
		{
			"RunScript"
			{
				"ScriptFile"    		"gawain_ability"
				"Function"      		"OnGalatineStart"
				"Target"				"POINT"
				"Damage"				"%damage"
				"BurnDamage"			"%dot_damage"
				"Max_range"				"%max_range"
				"Radius"				"%radius"
			}
			"ApplyModifier"
			{
				"ModifierName"			"modifier_excalibur_galatine_vfx"
				"Target"				"CASTER"
			}
		}
		
		"Modifiers"
		{		
			"modifier_excalibur_galatine_vfx"
			{
				"Duration"		"1.75"
				"OnCreated"
				{
					"AttachEffect"
					{
						"Target"			"TARGET"
						"EffectName"		"particles/custom/saber_excalibur_circle.vpcf"
						"EffectAttachType"	"follow_origin"
						"EffectRadius"		"400"
					}
				}
			}
			"modifier_excalibur_galatine_anim"
			{
				"OverrideAnimation"     "ACT_DOTA_CAST_ABILITY_2"	
				"Duration"				"2.2"
				"IsHidden"				"1"
				"Properties"
				{
					"MODIFIER_PROPERTY_OVERRIDE_ANIMATION_RATE"		"0.6"
				}
			}
			"modifier_excalibur_galatine_burn"
			{
				"EffectName"			"particles/units/heroes/hero_doom_bringer/doom_infernal_blade_debuff.vpcf"
				"EffectAttachType"		"follow_origin"			
				"IsDebuff"				"1"
				"Duration"				"%duration"
				"ThinkInterval"			"0.25"
				"OnIntervalThink"
				{
					"RunScript"
					{
						"ScriptFile"		"gawain_ability"
						"Function"			"OnBurnDamageTick"
						"Damage"			"%dot_damage"
					}
				}
			}
		}
	}

	//=======================================
	// Gawain : Detonate Excalibur Galatine
	//=======================================
	"gawain_excalibur_galatine_detonate"
	{
		// General		//------------------------------------------------------------------------------------------------------------
		"BaseClass"						"ability_datadriven"
		"MaxLevel"						"1"
		"AbilityBehavior"				"DOTA_ABILITY_BEHAVIOR_NO_TARGET | DOTA_ABILITY_BEHAVIOR_IMMEDIATE | DOTA_ABILITY_BEHAVIOR_IGNORE_PSEUDO_QUEUE | DOTA_ABILITY_BEHAVIOR_IGNORE_CHANNEL | DOTA_ABILITY_BEHAVIOR_HIDDEN"
		"AbilityTextureName"			"custom/gawain_excalibur_galatine"
		
		
		"AbilityCastPoint"				"0.0"
		"AbilityCooldown"				"5"
		"AbilityManaCost"				"0"

		"precache"
		{
		}

		"AbilitySpecial"
		{
		}
		
		"OnSpellStart"
		{
			"RunScript"
			{
				"ScriptFile"			"gawain_ability"
				"Function"				"OnGalatineDetonate"
			}
		}
	}

	//=================================================================================================================
	// Gawain : Excalibur Galatine Reborn
	//=================================================================================================================
	"gawain_excalibur_galatine_combo"
	{
		// General		//------------------------------------------------------------------------------------------------------------
		"BaseClass"						"ability_datadriven"
		"MaxLevel"						"1"
		"RequiredLevel"					"25"
		"LevelsBetweenUpgrades"			"1"
		"AbilityBehavior"				"DOTA_ABILITY_BEHAVIOR_POINT | DOTA_ABILITY_BEHAVIOR_AOE | DOTA_ABILITY_BEHAVIOR_HIDDEN"
		"AbilityUnitTargetType"			"DOTA_UNIT_TARGET_ALL"
		"AbilityUnitDamageType"			"DAMAGE_TYPE_MAGICAL"
		"AbilityTextureName"			"custom/gawain_galatine_combo"
		"AbilityCastAnimation" 			"ACT_DOTA_CAST_ABILITY_2"
		"AnimationPlaybackRate" 		"1.0"
		"AOERadius"						"%radius"

		
		"precache"
		{
			"particle"					"particles/units/heroes/hero_keeper_of_the_light/keeper_cast01.vpcf"
			"particle"					"particles/units/heroes/hero_lina/lina_spell_light_strike_array.vpcf"
			"particle"					"particles/custom/gawain/gawain_excalibur_galatine_orb.vpcf"
			"particle"					"particles/units/heroes/hero_ember_spirit/ember_spirit_hit.vpcf"
			"particle"					"particles/custom/saber_excalibur_circle.vpcf"
			"particle"					"particles/custom/gawain/gawain_combo.vpcf"
			"particle"					"particles/custom/screen_yellow_splash_gawain.vpcf"
			"particle"					"particles/custom/ruler/la_pucelle/la_pucelle_flame.vpcf"
			"particle"					"particles/custom/gawain/gawain_supernova_explosion.vpcf"
			"soundfile"					"soundevents/game_sounds_heroes/game_sounds_lina.vsndevts"
			"soundfile"					"soundevents/game_sounds_heroes/game_sounds_enigma.vsndevts"
		}
		
		"AbilityCastPoint"				"0.15"
		"AbilityCooldown"				"150"
		"AbilityManaCost"				"800"
		"AbilityCastRange"				"1500"
		
		"AbilitySpecial"
		{
			"01"
			{
				"var_type"				"FIELD_FLOAT"
				"cast_delay"			"4.0"
			}
			"02"
			{
				"var_type"				"FIELD_FLOAT"
				"damage"				"2750"
			}
			"03"
			{
				"var_type"				"FIELD_INTEGER"
				"radius"				"700"
			}
			"04"
			{
				"var_type"				"FIELD_INTEGER"
				"dot_damage"			"200"
			}
			"05"
			{
				"var_type"				"FIELD_INTEGER"
				"duration"				"5"
			}
			"06"
			{
				"var_type"				"FIELD_INTEGER"
				"max_range"				"2000"
			}
		}
		
		"OnSpellStart"
		{
			"RunScript"
			{
				"ScriptFile"    		"abilities/gawain/excalibur_galatine_combo"
				"Function"      		"OnGalatineStart"
				"Target"				"POINT"
				"Damage"				"%damage"
				"BurnDamage"			"%dot_damage"
				"Max_range"				"%max_range"
				"Radius"				"%radius"
			}
			"ApplyModifier"
			{
				"ModifierName"			"modifier_excalibur_galatine_vfx"
				"Target"				"CASTER"
			}
		}
		
		"Modifiers"
		{		
			"modifier_excalibur_galatine_vfx"
			{
				"Duration"		"1.75"
				"OnCreated"
				{
					"AttachEffect"
					{
						"Target"			"TARGET"
						"EffectName"		"particles/custom/saber_excalibur_circle.vpcf"
						"EffectAttachType"	"follow_origin"
						"EffectRadius"		"400"
					}
				}
			}
			"modifier_excalibur_galatine_anim"
			{
				"OverrideAnimation"     "ACT_DOTA_CAST_ABILITY_2"	
				"Duration"				"5"
				"IsHidden"				"1"
				"Properties"
				{
					"MODIFIER_PROPERTY_OVERRIDE_ANIMATION_RATE"		"0.2"
				}
			}
			"modifier_excalibur_galatine_burn"
			{
				"EffectName"			"particles/units/heroes/hero_doom_bringer/doom_infernal_blade_debuff.vpcf"
				"EffectAttachType"		"follow_origin"			
				"IsDebuff"				"1"
				"Duration"				"%duration"
				"ThinkInterval"			"0.25"
				"OnIntervalThink"
				{
					"RunScript"
					{
						"ScriptFile"		"gawain_ability"
						"Function"			"OnBurnDamageTick"
						"Damage"			"%dot_damage"
					}
				}
			}
			"modifier_galatine_combo_cd"
			{
				"IsDebuff"		"1"
			}
		}
	}

	//=======================================
	// Gawain : Detonate Excalibur Galatine
	//=======================================
	"gawain_excalibur_galatine_detonate_combo"
	{
		// General		//------------------------------------------------------------------------------------------------------------
		"BaseClass"						"ability_datadriven"
		"MaxLevel"						"1"
		"AbilityBehavior"				"DOTA_ABILITY_BEHAVIOR_NO_TARGET | DOTA_ABILITY_BEHAVIOR_IMMEDIATE | DOTA_ABILITY_BEHAVIOR_IGNORE_PSEUDO_QUEUE | DOTA_ABILITY_BEHAVIOR_IGNORE_CHANNEL | DOTA_ABILITY_BEHAVIOR_HIDDEN"
		"AbilityTextureName"			"custom/gawain_galatine_combo"
		
		
		"AbilityCastPoint"				"0.0"
		"AbilityCooldown"				"5"
		"AbilityManaCost"				"0"

		"precache"
		{
		}

		"AbilitySpecial"
		{
		}
		
		"OnSpellStart"
		{
			"RunScript"
			{
				"ScriptFile"			"abilities/gawain/excalibur_galatine_combo"
				"Function"				"OnGalatineDetonate"
			}
		}
	}
	

	//=======================================
	// Gawain Attribute : Blessing of Fairy
	//=======================================
	"gawain_attribute_blessing_of_fairy"
	{
		// General		//------------------------------------------------------------------------------------------------------------
		"BaseClass"						"ability_datadriven"
		"MaxLevel"						"1"
		"AbilityBehavior"				"DOTA_ABILITY_BEHAVIOR_NO_TARGET | DOTA_ABILITY_BEHAVIOR_IMMEDIATE | DOTA_ABILITY_BEHAVIOR_IGNORE_PSEUDO_QUEUE | DOTA_ABILITY_BEHAVIOR_IGNORE_CHANNEL"
		"AbilityTextureName"			"custom/gawain_attribute_blessing_of_fairy"
		
		
		"AbilityCastPoint"				"0.0"
		"AbilityCooldown"				"9999"
		"AbilityManaCost"				"12"

		"precache"
		{
		}

		"AbilitySpecial"
		{
			"01"
			{
				"var_type"				"FIELD_INTEGER"
				"health_restored"		"350"
			}
			"02"
			{
				"var_type"				"FIELD_INTEGER"
				"regen_amount"			"100"
			}
			"03"
			{
				"var_type"				"FIELD_INTEGER"
				"duration"				"5"
			}
		}
		
		"OnSpellStart"
		{
			"RunScript"
			{
				"ScriptFile"	"gawain_ability"
				"Function"		"OnFairyAcquired"
			}
		}

		"Modifiers"
		{

		}
	}
	
	//=======================================================
	// Gawain Attribute : Resurrected Sword of Victory
	//=======================================================
	"gawain_attribute_res_sov"
	{
		// General		//------------------------------------------------------------------------------------------------------------
		"BaseClass"						"ability_datadriven"
		"MaxLevel"						"1"
		"AbilityBehavior"				"DOTA_ABILITY_BEHAVIOR_NO_TARGET | DOTA_ABILITY_BEHAVIOR_IMMEDIATE | DOTA_ABILITY_BEHAVIOR_IGNORE_PSEUDO_QUEUE | DOTA_ABILITY_BEHAVIOR_IGNORE_CHANNEL"
		"AbilityTextureName"			"custom/gawain_attribute_dawnbringer"
		
		
		"AbilityCastPoint"				"0.0"
		"AbilityCooldown"				"9999"
		"AbilityManaCost"				"17"

		"precache"
		{
		}

		"AbilitySpecial"
		{
			"01"
			{
				"var_type"				"FIELD_INTEGER"
				"damage"				"250"
			}
			"02"
			{
				"var_type"				"FIELD_INTEGER"
				"combo_damage"			"1500"
			}
			"03"
			{
				"var_type"				"FIELD_INTEGER"
				"fire_trail_duration"	"3"
			}
		}
		
		"OnSpellStart"
		{
			"RunScript"
			{
				"ScriptFile"		"gawain_ability"
				"Function"			"OnSoVAcquired"
			}
		}
	}

	//=======================================================
	// Gawain Attribute : Numeral of the Saint
	//=======================================================
	"gawain_attribute_saint_num"
	{
		// General		//------------------------------------------------------------------------------------------------------------
		"BaseClass"						"ability_datadriven"
		"MaxLevel"						"1"
		"AbilityBehavior"				"DOTA_ABILITY_BEHAVIOR_NO_TARGET | DOTA_ABILITY_BEHAVIOR_IMMEDIATE | DOTA_ABILITY_BEHAVIOR_IGNORE_PSEUDO_QUEUE | DOTA_ABILITY_BEHAVIOR_IGNORE_CHANNEL"
		"AbilityTextureName"			"custom/gawain_saint"	
		"AbilityCastPoint"				"0.0"
		"AbilityCooldown"				"9999"
		"AbilityManaCost"				"16"

		"precache"
		{
		}

		"AbilitySpecial"
		{
			"01"
			{
				"var_type"				"FIELD_FLOAT"
				"stun_duration"			"1.0"
			}
			"02"
			{
				"var_type"				"FIELD_FLOAT"
				"channel_required"		"1.5"
			}
		}
		
		"OnSpellStart"
		{
			"RunScript"
			{
				"ScriptFile"		"gawain_ability"
				"Function"			"OnNoSAcquired"
			}
		}
	}

	//=======================================
	// Gawain Attribute : Belt of Bertilak
	//=======================================
	"gawain_attribute_belt"
	{
		// General		//------------------------------------------------------------------------------------------------------------
		"BaseClass"						"ability_datadriven"
		"MaxLevel"						"1"
		"AbilityBehavior"				"DOTA_ABILITY_BEHAVIOR_NO_TARGET | DOTA_ABILITY_BEHAVIOR_IMMEDIATE | DOTA_ABILITY_BEHAVIOR_IGNORE_PSEUDO_QUEUE | DOTA_ABILITY_BEHAVIOR_IGNORE_CHANNEL"
		"AbilityTextureName"			"custom/gawain_belt"
		
		
		"AbilityCastPoint"				"0.0"
		"AbilityCooldown"				"9999"
		"AbilityManaCost"				"16"

		"precache"
		{
		}

		"AbilitySpecial"
		{
			"01"
			{
				"var_type"				"FIELD_INTEGER"
				"heat_damage"			"8"
			}
			"02"
			{
				"var_type"				"FIELD_INTEGER"
				"blade_aoe"				"250"
			}
		}
		
		"OnSpellStart"
		{
			"RunScript"
			{
				"ScriptFile"			"gawain_ability"
				"Function"				"OnBeltAcquired"
			}
		}
	}
}